#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d I-I I-II I-III I-IV I-V
bspc monitor HDMI-3 -d II-I II-II II-III II-IV II-V
bspc monitor DP-1 -d III-I III-II III-III III-IV III-V

bspc config border_width         3

#bspc config window_gap         28
bspc config window_gap 			16

bspc config focus_follows_pointer     false
bspc config ignore_wemh_focus        true

#bspc config -m DP-2 top_padding 30
bspc config -m DP-2 top_padding 45

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config automatic_scheme longest_side

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on

bspc rule -a zoom state=floating
bspc rule -a Brave-browser state=floating
bspc rule -a discord state=pseudo_tiled desktop="^1"
bspc rule -a spotify state=pseudo_tiled desktop="^9"
bspc rule -a dolphin state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Thunar state=floating
bspc rule -a Gitkraken state=floating

bspc config normal_border_color  "#252525"
bspc config focused_border_color  "#0050B7"
bspc config presel_feedback_color  "#89B8F7"

