#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d I II III IV V
bspc monitor HDMI-3 -d VI VII VIII
bspc monitor DP-1 -d IX X

bspc config border_width        3
bspc config window_gap         28

bspc config focus_follows_pointer     false
bspc config ignore_wemh_focus        true

bspc config -m DP-2 top_padding 30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config automatic_scheme longest_side

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on

bspc rule -a zoom state=floating
bspc rule -a Brave-browser state=floating
bspc rule -a discord state=pseudo_tiled desktop="^1"
bspc rule -a spotify state=pseudo_tiled desktop="^9"
bspc rule -a dolphin state=floating


bspc config normal_border_color  "#252525"
bspc config focused_border_color  "#0050B7"
bspc config presel_feedback_color  "#89B8F7"
