#!/bin/env zsh

alias cat='bat'
alias path='echo $PATH | tr ":" "\n"'

alias weather="curl wttr.in/Saskatoon"  # Check the weather
alias parrot="curl parrot.live"         # It's kinda fun

# Move up a level
alias ..="cd .."
alias cd..=".."

alias ~="cd ~"

# needs spotify-cli installed: https://github.com/pwittchen/spotify-cli-linux
alias playing="spotifycli --status"
alias play="spotifycli --play"
alias pause="spotifycli --pause"
alias skip="spotifycli --next"

# audio
alias volume="pulsemixer --get-volume | cut -d ' ' -f 1"
alias volumeup="pulsemixer --change-volume +5"
alias volumedown="pulsemixer --change-volume -5"
alias mute="pactl set-sink-mute @DEFAULT_SINK@ 1"
alias unmute="pactl set-sink-mute @DEFAULT_SINK@ 0"

# git
alias commit="git commit -S -m "
alias push="git push "
alias add="git add "
alias pull="git pull "
alias checkout="git checkout "
alias branch="git branch "
alias status="git status "
alias merge="git merge "
alias stash="git stash "
alias clone="git clone "
alias push-upstream="git push --set-upstream origin "
alias unstage="git restore --staged "

# XDG compliance
[[ -z $XDG_CONFIG_HOME ]] || {

    alias wget='wget --hts-file="$XDG_CACHE_HOME/wget-hsts"'
    alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'

}
